spring:
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5444}/${DB_NAME:company-db}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    pool:
      validation-query: 'SELECT 1'
      max-life-time: 3m
      max-idle-time: 5m
  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5444}/${DB_NAME:company-db}
    user: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
server:
  port: 8888